TEMPLATES = {
    "modern_professional": {
        "name": "Modern Professional",
        "description": "Navy headings, recruiter-friendly single column.",
        "accent": "#1e40af",
        "header": "#0f172a",
        "muted": "#475569",
        "sidebar": "",
        "sidebar_text": "#0f172a",
        "rule": "#1e40af",
        "order": "standard",
        "serif": False,
        "centered": False,
        "header_bar": False,
        "compact": False,
    },
    "minimal_ats": {
        "name": "Minimal ATS",
        "description": "Plain single column that parsers read reliably.",
        "accent": "#111827",
        "header": "#111827",
        "muted": "#374151",
        "sidebar": "",
        "sidebar_text": "#111827",
        "rule": "#111827",
        "order": "standard",
        "serif": False,
        "centered": True,
        "header_bar": False,
        "compact": True,
    },
    "corporate": {
        "name": "Corporate",
        "description": "Conservative navy header for enterprise roles.",
        "accent": "#0f2744",
        "header": "#0f2744",
        "muted": "#334155",
        "sidebar": "",
        "sidebar_text": "#0f2744",
        "rule": "#0f2744",
        "order": "standard",
        "serif": True,
        "centered": True,
        "header_bar": True,
        "compact": False,
    },
    "executive": {
        "name": "Executive",
        "description": "Wide margins and refined serif headings.",
        "accent": "#b45309",
        "header": "#1c1917",
        "muted": "#44403c",
        "sidebar": "",
        "sidebar_text": "#1c1917",
        "rule": "#b45309",
        "order": "standard",
        "serif": True,
        "centered": True,
        "header_bar": False,
        "compact": False,
        "wide": True,
    },
    "modern_two_column": {
        "name": "Modern Two-Column",
        "description": "Dark sidebar for contact and skills.",
        "accent": "#0f766e",
        "header": "#f8fafc",
        "muted": "#cbd5e1",
        "sidebar": "#0f172a",
        "sidebar_text": "#e2e8f0",
        "rule": "#0f766e",
        "order": "two_column",
        "serif": False,
        "centered": False,
        "header_bar": False,
        "compact": False,
    },
    "tech_data": {
        "name": "Tech / Data",
        "description": "Compact teal layout with skill emphasis.",
        "accent": "#0f766e",
        "header": "#134e4a",
        "muted": "#3f3f46",
        "sidebar": "",
        "sidebar_text": "#134e4a",
        "rule": "#0f766e",
        "order": "standard",
        "serif": False,
        "centered": False,
        "header_bar": False,
        "compact": True,
    },
    "clean_graduate": {
        "name": "Clean Graduate",
        "description": "Education-first layout for internships.",
        "accent": "#1d4ed8",
        "header": "#1e3a8a",
        "muted": "#475569",
        "sidebar": "",
        "sidebar_text": "#1e3a8a",
        "rule": "#1d4ed8",
        "order": "graduate",
        "serif": False,
        "centered": True,
        "header_bar": False,
        "compact": False,
    },
}


def list_templates():
    return [{"id": key, **value} for key, value in TEMPLATES.items()]


def get_template(template_id):
    return TEMPLATES.get(template_id) or TEMPLATES["modern_professional"]
