from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer
)

from reportlab.lib.styles import getSampleStyleSheet

from reportlab.lib.enums import TA_CENTER

from reportlab.lib.colors import HexColor


def generate_report(filepath, analysis):

    doc = SimpleDocTemplate(filepath)

    styles = getSampleStyleSheet()

    title = styles["Heading1"]
    title.alignment = TA_CENTER
    title.textColor = HexColor("#2563eb")

    heading = styles["Heading2"]

    normal = styles["BodyText"]

    story = []

    # ---------------- TITLE ----------------

    story.append(
        Paragraph(
            "TalentIQ AI",
            title
        )
    )

    story.append(
        Paragraph(
            "Professional Resume Analysis Report",
            heading
        )
    )

    story.append(Spacer(1,20))

    # ---------------- SCORES ----------------

    story.append(
        Paragraph(
            "<b>Resume Score :</b> {} / 100".format(
                analysis["resume_score"]
            ),
            normal
        )
    )

    story.append(
        Paragraph(
            "<b>ATS Score :</b> {} / 100".format(
                analysis["ats_score"]
            ),
            normal
        )
    )

    story.append(
        Paragraph(
            "<b>Career Match :</b> {} %".format(
                analysis["job_match"]
            ),
            normal
        )
    )

    story.append(
        Paragraph(
            "<b>Predicted Career :</b> {}".format(
                analysis["predicted_job"]
            ),
            normal
        )
    )

    story.append(Spacer(1,20))

    # ---------------- SKILLS ----------------

    story.append(
        Paragraph(
            "Detected Skills",
            heading
        )
    )

    for skill in analysis["skills"]:

        story.append(
            Paragraph(
                "• " + skill,
                normal
            )
        )

    story.append(Spacer(1,20))

    # ---------------- MISSING SKILLS ----------------

    story.append(
        Paragraph(
            "Missing Skills",
            heading
        )
    )

    if isinstance(analysis["skill_gap"], dict):

        missing = analysis["skill_gap"].get("missing_skills", [])

    else:

        missing = analysis["skill_gap"]

    for skill in missing:

        story.append(
            Paragraph(
                "• " + skill,
                normal
            )
        )

    story.append(Spacer(1,20))

    # ---------------- AI SUMMARY ----------------

    story.append(
        Paragraph(
            "AI Recommendation",
            heading
        )
    )

    story.append(
        Paragraph(
            analysis["ai_summary"],
            normal
        )
    )

    story.append(Spacer(1,20))

    story.append(
        Paragraph(
            "Generated by TalentIQ AI",
            heading
        )
    )

    doc.build(story)